kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
  branch:
    - main
    - feature/ci
    - cli/*

steps:
  - name: build-cli
    image: gcc:12
    commands:
      - apt-get update && apt-get install -y nlohmann-json3-dev libcurl4-openssl-dev libminizip-dev doctest-dev
      - cd cli && ./configure.sh -d && make oki-test
