kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
  branch:
    - main
    - feature/ci
    - cli/*

steps:
  - name: build-cli
    image: hub.codefirst.iut.uca.fr/clement.freville2/oki-build-image:latest
    commands:
      - cd cli && ./configure.sh && make

  - name: test-cli
    image: hub.codefirst.iut.uca.fr/clement.freville2/oki-build-image:latest
    commands:
      - cd cli && make oki-test
      - ./oki-test
    depends_on:
      - build-cli
