kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
  branch:
    - main
    - feature/ci
    - cli/*

steps:
  - name: build-cli
    image: hub.codefirst.iut.uca.fr/clement.freville2/oki-build-image:latest
    commands:
      - cd cli && make

  - name: test-cli
    image: hub.codefirst.iut.uca.fr/clement.freville2/oki-build-image:latest
    commands:
      - cd cli && make oki-test
      - ./oki-test
    depends_on:
      - build-cli

  - name: build-book
    image: hub.codefirst.iut.uca.fr/clement.freville2/oki-build-image:latest
    commands:
      - cd doc && mdbook build

  - name: deploy-doc
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-docdeployer
    failure: ignore
    commands:
      - doc/entrypoint.sh
    depends_on:
      - build-book
    when:
      branch:
        - main
        - doc/setup
