kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
  - name: build-cli
    image: hub.codefirst.iut.uca.fr/clement.freville2/oki-build-image:latest
    commands:
      - cd cli && make

  - name: test-cli
    image: hub.codefirst.iut.uca.fr/clement.freville2/oki-build-image:latest
    commands:
      - cd cli && make oki-test
      - ./oki-test
    depends_on:
      - build-cli

  - name: lint-web
    image: ghcr.io/phpstan/phpstan:latest-php8.2
    commands:
      - cd web
      - phpstan analyse src --level 2

  - name: build-book
    image: hub.codefirst.iut.uca.fr/clement.freville2/oki-build-image:latest
    commands:
      - cd doc && mdbook build

  - name: deploy-doc
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-docdeployer
    failure: ignore
    commands:
      - doc/entrypoint.sh
    depends_on:
      - build-book
    when:
      branch:
        - main
        - doc/setup

  - name: swagger-doc
    image: hub.codefirst.iut.uca.fr/maxime.batista/codefirst-docdeployer
    failure: ignore
    volumes:
      - name: docs
        path: /docs
    commands:
      - ln -s oki-api.yaml swagger.yml
      - /entrypoint.sh --type swagger --dir . --dest swagger

volumes:
  - name: docs
    temp: { }
