kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
  branch:
    - main
    - feature/ci
    - cli/*
    - doc/*
    - web/*
    - ci/*

steps:
  - name: build-cli
    image: hub.codefirst.iut.uca.fr/clement.freville2/oki-build-image:latest
    commands:
      - cd cli && make

  - name: test-cli
    image: hub.codefirst.iut.uca.fr/clement.freville2/oki-build-image:latest
    commands:
      - cd cli && make oki-test
      - ./oki-test
    depends_on:
      - build-cli

  - name: lint-web
    image: ghcr.io/phpstan/phpstan:latest-php8.2
    commands:
      - cd web
      - phpstan analyse src --level 3

  - name: deploy-swagger
    image: hub.codefirst.iut.uca.fr/maxime.batista/codefirst-docdeployer:0.2
    settings:
      source: ./oki-api.yaml
      target: api
      transform: swagger
    failure: ignore
    when:
      branch:
        - main
        - ci/*

  - name: build-book
    image: ghcr.io/peaceiris/mdbook:v0.4.34
    commands:
      - mdbook build doc -d build

  - name: deploy-book
    image: hub.codefirst.iut.uca.fr/maxime.batista/codefirst-docdeployer:0.2
    settings:
      source: doc/build
      target: book
    failure: ignore
    depends_on: [build-book]
    when:
      branch:
        - main
        - ci/*
