openapi: 3.0.3
info:
  title: OKI
  description: Open pacKage Installer
  version: 1.0.0
servers:
  - url: 'https://oki-pkg.dev'
    description: Staging instance
paths:
  /?api=list:
    get:
      summary: List all available packages
      responses:
        200:
          description: All available packages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Package'
  /?api=info&package={name}:
    get:
      summary: Get package details and all its versions
      parameters:
        - name: name
          in: path
          description: Short name of an existing package
          required: true
          schema:
            type: string
      responses:
        200:
          description: Package details and all its versions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageDetails'
        400:
          description: Invalid package name
  /?api=version&name={name}&version={version}:
    get:
      summary: Get a download url
      parameters:
        - name: name
          in: path
          description: Short name of an existing package
          required: true
          schema:
            type: string
        - name: version
          in: path
          description: Existing version
          required: true
          schema:
            type: string
      responses:
        200:
          description: The download url
          content:
            application/json:
              schema:
                type: string
                example: packages/l/linked-list_1.3.zip
        400:
          description: Invalid package name or version

components:
  schemas:
    Package:
      type: object
      properties:
        short_name:
          type: string
          example: linked-list
        description:
          type: string
          example: Implementation of an int linked list data structure in C
    PackageDetails:
      allOf:
        - $ref: '#/components/schemas/Package'
        - type: object
          properties:
            versions:
              type: array
              items:
                $ref: '#/components/schemas/PackageVersion'
    PackageVersion:
      type: object
      properties:
        identifier:
          type: string
          example: '1.3'
        published_date:
          type: string
          example: 2022-10-20 15:32:49
        download_url:
          type: string
          example: packages/l/linked-list_1.3.zip
